<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
    <xsl:output method="xml" indent="yes"/>
    <xsl:param name="account"/>
    <xsl:template match="/">
        <ShipOrder xmlns="kaoto">
            <xsl:attribute name="OrderId">
                <xsl:value-of select="upper-case($account/Account/@AccountId)"/>
            </xsl:attribute>
            <OrderPerson>
                <xsl:value-of select="$account/Account/Name"/>
            </OrderPerson>
            <ShipTo xmlns="">
                <Name>
                    <xsl:value-of select="$account/Account/Name"/>
                </Name>
                <Address>
                    <xsl:value-of select="$account/Account/Address"/>
                </Address>
                <City>
                    <xsl:value-of select="$account/Account/City"/>
                </City>
                <Country>
                    <xsl:value-of select="$account/Account/Country"/>
                </Country>
            </ShipTo>
            <xsl:for-each select="/Cart/Item">
                <Item xmlns="">
                    <Title>
                        <xsl:value-of select="Title"/>
                    </Title>
                    <Note>
                        <xsl:value-of select="Note"/>
                    </Note>
                    <Quantity>
                        <xsl:value-of select="Quantity"/>
                    </Quantity>
                    <Price>
                        <xsl:value-of select="Price"/>
                    </Price>
                </Item>
            </xsl:for-each>
        </ShipOrder>
    </xsl:template>
</xsl:stylesheet>