<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
        <Hello>
            <xsl:value-of select="'Hello', /Account/Name, /Account/Address, /Account/City, 'MA', /Account/Country"/>
        </Hello>
    </xsl:template>
</xsl:stylesheet>