<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
        <ShipOrder xmlns="io.kaoto.datamapper.poc.test">
            <xsl:attribute name="OrderId">
                <xsl:value-of select="/hash/id"/>
            </xsl:attribute>
            <ShipTo xmlns="">
                <Name>
                    <xsl:value-of select="/hash/uid"/>
                </Name>
                <Address>
                    <xsl:value-of select="/hash/account-number"/>
                </Address>
                <City>
                    <xsl:value-of select="/hash/bank-name"/>
                </City>
                <Country>
                    <xsl:value-of select="/hash/swift-bic"/>
                </Country>
            </ShipTo>
        </ShipOrder>
    </xsl:template>
</xsl:stylesheet>

